import { useState, useEffect, useRef } from 'react'
import { fetchGeoBatch, getCountryCached } from '../utils/getCountry'

let cachedProxies = null

// proxies.json is generated by checker/ and committed to public/ by GitHub Actions
const PROXIES_JSON = import.meta.env.BASE_URL + 'proxies.json'

// Fallback: fetch raw list if proxies.json doesn't exist yet
const RAW_SOURCE = 'https://raw.githubusercontent.com/SoliSpirit/mtproto/refs/heads/master/all_proxies.txt'

function isValidPort(port) {
  const n = parseInt(port, 10)
  return !isNaN(n) && n > 0 && n <= 65535
}

function parseRawList(text) {
  return text
    .split('\n')
    .map((line, i) => {
      line = line.trim()
      if (!line) return null
      try {
        const qs     = line.includes('?') ? line.split('?')[1] : ''
        const p      = new URLSearchParams(qs)
        const server = p.get('server')
        const port   = p.get('port')
        const secret = p.get('secret')
        if (!server || !port || !secret || !isValidPort(port)) return null
        return { id: i, server, port, secret, tgLink: `tg://proxy?server=${server}&port=${port}&secret=${secret}` }
      } catch { return null }
    })
    .filter(Boolean)
}

async function loadProxies() {
  // Try pre-checked list first (generated by GitHub Actions)
  try {
    const res = await fetch(PROXIES_JSON)
    if (res.ok) {
      const data = await res.json()
      if (Array.isArray(data) && data.length > 0) return data
    }
  } catch { /* fall through */ }

  // Fallback: raw list (no liveness check, shows all valid-port proxies)
  const res  = await fetch(RAW_SOURCE)
  const text = await res.text()
  return parseRawList(text)
}

export function useProxies() {
  const [proxies,  setProxies]  = useState(cachedProxies ?? [])
  const [loading,  setLoading]  = useState(cachedProxies === null)
  const [error,    setError]    = useState(null)
  const cancelRef = useRef(false)

  async function load() {
    cancelRef.current = false
    try {
      let raw = cachedProxies
      if (!raw) {
        raw = await loadProxies()
      }

      if (cancelRef.current) return

      // Show proxies immediately
      setProxies(raw)
      setLoading(false)

      // Fetch geo silently in background (used only for ping estimation)
      await fetchGeoBatch(raw.map(p => p.server))

      if (cancelRef.current) return

      // Re-render with countryCode for accurate ping estimates
      const enriched = raw.map(p => ({
        ...p,
        countryCode: getCountryCached(p.server).countryCode ?? null,
      }))

      cachedProxies = enriched
      setProxies(enriched)

    } catch (err) {
      if (!cancelRef.current) {
        setError(err.message)
        setLoading(false)
      }
    }
  }

  useEffect(() => {
    load()
    return () => { cancelRef.current = true }
  }, [])

  function retry() {
    cachedProxies = null
    cancelRef.current = true
    setTimeout(() => {
      setProxies([])
      setLoading(true)
      setError(null)
      load()
    }, 50)
  }

  return { proxies, loading, error, retry }
}
